### ISSUE TITLE
Add MCRN: MacaronSwap Token

### ISSUE THREAD

**Issue by chocofalls** [sushiswap/default-token-list#103]
- [X] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

Token Address: 0xacb2d47827c9813ae26de80965845d80935afd0b
Token Name (from contract): MacaronSwap Token
Token Decimals (from contract): 18
Token Symbol (from contract): MCRN
PancakeSwap V2 Pair Address of Token: 0xe8d5d81dac092ae61d097f84efe230759bf2e522 MCRN-BNB Pair

Link to the official homepage of token: https://www.macaronswap.finance/ also https://macaronswap.com/
Link to CoinMarketCap or CoinGecko page of token:
https://coinmarketcap.com/currencies/macaronswap/
https://www.coingecko.com/en/coins/macaronswap

**Comment by matthewlilley** [comment]
Added!
