### ISSUE TITLE
Add {CQT}: {Covalent Query Token}

### ISSUE THREAD

**Issue by anadi2311** [sushiswap/default-token-list#117]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xd417144312dbf50465b1c641d016962017ef6240
Token Name (from contract): Covalent Query Token
Token Decimals (from contract): 18
Token Symbol (from contract):  CQT
SushiSwap V2 Pair Address of Token: 0x17890DeB188F2dE6C3e966e053dA1C9a111Ed4A5

Link to the official homepage of token: https://www.covalenthq.com/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/covalent

**Comment by matthewlilley** [comment]
Added
