### ISSUE TITLE
Add RNBW: Rainbow Token

### ISSUE THREAD

**Issue by ernestpascual** [sushiswap/default-token-list#121]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xe94b97b6b43639e238c851a7e693f50033efd75c 
Token Name (from contract): Rainbow Token
Token Decimals (from contract): 18
Token Symbol (from contract):  RNBW
SushiSwap V2 Pair Address of Token: 0xdb30d3f9b55bd57271d171fec708b575aa940082

Link to the official homepage of token: https://www.halodao.com/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/rainbow-token

**Comment by jiro-ono** [comment]
Added
