### ISSUE TITLE
Add pCWS: PolyCrowns 

### ISSUE THREAD

**Issue by SchneiderNejc** [sushiswap/default-token-list#122]
- [X] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xbcf39f0edda668c58371e519af37ca705f2bfcbd
Token Name (from contract): PolyCrowns 
Token Decimals (from contract): 18
Token Symbol (from contract): pCWS
SushiSwap V2 Pair Address of Token:  0x777b0c17d6f2a3aa21f791d73c5a26eb56dd5292

Link to the official homepage of token: https://bsc.game.seascape.network/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/crowns/

**Comment by jiro-ono** [comment]
@SchneiderNejc what network is this token on??

**Comment by SchneiderNejc** [comment]
BSC network.
However we are also listed on ethereum, should I file a new issue for that ?
