### ISSUE TITLE
Add LMA: LMA-Art-Gallery

### ISSUE THREAD

**Issue by BrunoMarshall** [sushiswap/default-token-list#143]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x7d0546dBb1Dca8108d99Aa389A8e9Ce0C40B2370
Token Name (from contract): LMA-Art-Gallery
Token Decimals (from contract): 18
Token Symbol (from contract): LMA
SushiSwap V2 Pair Address of Token: 

Link to the official homepage of token: https://lma-art-gallery.com/
Link to CoinMarketCap or CoinGecko page of token:

**Comment by jiro-ono** [comment]
no pair
