### ISSUE TITLE
Add {STARL}: {StarLink_MetaVerse}

### ISSUE THREAD

**Issue by jilky** [sushiswap/default-token-list#171]
- [x ] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x ] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x8e6cd950ad6ba651f6dd608dc70e5886b1aa6b24
Token Name (from contract): StarLink
Token Decimals (from contract): 18
Token Symbol (from contract): STARL
SushiSwap V2 Pair Address of Token: 
Amount of STARL: 2,796,071,449,898.350 STARL
Uniswap % Volume: 98.5314%
Uniswap 24 hour volume: $32,505,732.00

Link to the official homepage of token: https://www.starltoken.com/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/starlink
![256x256 STARL LOGO](https://user-images.githubusercontent.com/17280090/127651454-7b434280-cfe1-49f8-8c53-7db1e6173859.jpg)

**Comment by jiro-ono** [comment]
There's no pair currently
