### ISSUE TITLE
Add {BEL}: {Bella}

### ISSUE THREAD

**Issue by LacroixW** [sushiswap/default-token-list#179]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xee800b277a96b0f490a1a732e1d6395fad960a26
Token Name (from contract): ARPA Token
Token Decimals (from contract): 18
Token Symbol (from contract): ARPA
SushiSwap V2 Pair Address of Token: 0x590F5E967d73eA06DAE9aED2788108DCF52dA269

Link to the official homepage of token: https://arpachain.io/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/arpa-chain/

**Comment by jiro-ono** [comment]
Is this for ARPA  or BEL?
