### ISSUE TITLE
Add {polyBUNNY}: {Polygon BUNNY Token}

### ISSUE THREAD

**Issue by ian9054** [sushiswap/default-token-list#184]
- [V] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [V] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [V] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon Network
Token Address (checkSum): 0x4C16f69302CcB511c5Fac682c7626B9eF0Dc126a
Token Name (from contract): Polygon BUNNY Token
Token Decimals (from contract): 18
Token Symbol (from contract): polyBUNNY
SushiSwap V2 Pair Address of Token: 0xc5666D43F06C073E869bce02407569f578B2072D

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/178
Link to the official homepage of token: https://polygon.pancakebunny.finance/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/pancake-bunny-polygon
Link to official Twitter account: https://twitter.com/pancakebunnyfin

**Comment by jiro-ono** [comment]
Added
