### ISSUE TITLE
Add BPT: BlackPool Token

### ISSUE THREAD

**Issue by hatashiyamatomo** [sushiswap/default-token-list#194]
Network:
Token Address (checkSum): 0x0eC9F76202a7061eB9b3a7D6B59D36215A7e37da
Token Name (from contract): BlackPool Token
Token Decimals (from contract): 18
Token Symbol (from contract): BPT
SushiSwap V2 Pair Address of Token:  https://app.sushi.com/add/0x0eC9F76202a7061eB9b3a7D6B59D36215A7e37da/ETH

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/tree/master/blockchains/ethereum/assets/0x0eC9F76202a7061eB9b3a7D6B59D36215A7e37da
Link to the official homepage of token: https://blackpool.finance/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/blackpool-token
Link to official Twitter account: https://twitter.com/BlackpoolHQ

**Comment by jiro-ono** [comment]
Should already be on the list
