### ISSUE TITLE
Add{BANANA}: {CyberKongz BANANA token} 

### ISSUE THREAD

**Issue by SebsSebsSebs** [sushiswap/default-token-list#197]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0xe2311ae37502105b442bbef831e9b53c5d2e9b3b
Token Name (from contract):  Banana 
Token Decimals (from contract): 18
Token Symbol (from contract): BANANA 
SushiSwap V2 Pair Address of Token:  0xcfa9a297a406a48d1137172c18de04c944b47ba9

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/compare/master...SebsSebsSebs:master
Link to the official homepage of token: https://www.cyberkongz.com/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/banana
Link to official Twitter account: https://twitter.com/CyberKongz

**Comment by jiro-ono** [comment]
Added
