### ISSUE TITLE
Add HNY: HNY

### ISSUE THREAD

**Issue by befitsandpiper** [sushiswap/default-token-list#2]
- [x] I understand that token listing is not required to use the Uniswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xc3589f56b6869824804a5ea29f2c9886af1b0fce
Token Name (from contract): HNY
Token Decimals (from contract): 18 decimals
Token Symbol (from contract): HNY
Sushiwap V2 Pair Address of Token: 0xdae3ac391756d65fff76502ff4d1d7697a991c5a

Link to the official homepage of token: https://wiki.1hive.org/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/honey

**Comment by matthewlilley** [comment]
Added!
