### ISSUE TITLE
Add STND: Standard on Polygon

### ISSUE THREAD

**Issue by hskang9** [sushiswap/default-token-list#203]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0x08BE454de533509e8832B257116C5506E55b0b64
Token Name (from contract): Standard
Token Decimals (from contract): 18
Token Symbol (from contract): STND
SushiSwap V2 Pair Address of Token: 0x7e24a40439fabcf42ef75099bcae123c6d8dc0e9

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/201
Link to the official homepage of token: https://standard.tech
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/standard-protocol
Link to official Twitter account: https://twitter.com/standarddefi

**Comment by jiro-ono** [comment]
Added
