### ISSUE TITLE
Add {1ONE} : {Harmony ONE}

### ISSUE THREAD

**Issue by lijiang2087** [sushiswap/default-token-list#21]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0xd5cd84d6f044abe314ee7e414d37cae8773ef9d3
Token Name (from contract): Harmony ONE
Token Decimals (from contract): 18
Token Symbol (from contract): 1ONE
SushiSwap V2 Pair Address of Token: 0x986627db5e4aae987f580feb63d475992e5ac0ae

Link to the official homepage of token: https://harmony.one
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/harmony/

**Comment by matthewlilley** [comment]
Added!
