### ISSUE TITLE
Add ARBYS: Arbys

### ISSUE THREAD

**Issue by MasterDicc** [sushiswap/default-token-list#214]
- [ x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [ x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x86A1012d437BBFf84fbDF62569D12d4FD3396F8c
Token Name (from contract): Arbys
Token Decimals (from contract): 18
Token Symbol (from contract): ARBYS
SushiSwap V2 Pair Address of Token: 0xf4a738d9cae344cea4165f335d478493a7946f24

Link to sushiswap/assets PR:
Link to the official homepage of token: arbee.info
Link to CoinMarketCap or CoinGecko page of token: not approved
Link to official Twitter account: https://twitter.com/ArbysToken

**Comment by jiro-ono** [comment]
Added
