### ISSUE TITLE
Add CRD: CryptalDash

### ISSUE THREAD

**Issue by CRDGit** [sushiswap/default-token-list#23]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address:  0xcaaa93712bdac37f736c323c93d4d5fdefcc31cc
Token Name (from contract):  CryptalDash 
Token Decimals (from contract): 18
Token Symbol (from contract): CRD 
SushiSwap V2 Pair Address of Token:  https://app.sushi.com/pair/0xd3f85d18206829f917929bbbf738c1e0ce9af7fc

Link to the official homepage of token: https://www.crdtoken.org
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/cryptaldash#markets

**Comment by matthewlilley** [comment]
Added!
