### ISSUE TITLE
ROM: ROMCOIN

### ISSUE THREAD

**Issue by justmeandyou** [sushiswap/default-token-list#234]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:

Token Name (from contract):secondromcoin
Token Decimals (from contract):8
Token Symbol (from contract):secondromcoin
SushiSwap V2 Pair Address of Token:no

Link to sushiswap/assets PR:no
Link to the official homepage of token:https://livthemonkey.wixsite.com/romcoin-1
Link to CoinMarketCap or CoinGecko page of token:no
Link to official Twitter account:no

**Comment by justmeandyou** [comment]
thank u its very complicated

**Comment by justmeandyou** [comment]
qhat do i do next

**Comment by jiro-ono** [comment]
Sorry don't think it makes sense to add the token to the token list at this time
