### ISSUE TITLE
Add BNPL: BNPL Pay on Ethereum

### ISSUE THREAD

**Issue by cryptopoly** [sushiswap/default-token-list#245]
- [ Y] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [ Y] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [ Y] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x84d821F7FbDD595c4C4A50842913e6b1E07d7a53
Token Name (from contract): BNPL Pay
Token Decimals (from contract): 18
Token Symbol (from contract): BNPL
SushiSwap V2 Pair Address of Token: https://analytics.sushi.com/pairs/0x817211d408fbc19193e482f4900354e4cc894a44

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/229
Link to the official homepage of token: https://bnplpay.io
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/bnpl-pay
Link to official Twitter account: https://twitter.com/bnplpay

**Comment by cryptopoly** [comment]
Added CoinGecko link

**Comment by jiro-ono** [comment]
Added
