### ISSUE TITLE
Add Polk: Polkamarkets on Moonriver

### ISSUE THREAD

**Issue by rsmarques** [sushiswap/default-token-list#272]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: **Moonriver**
Token Address (checkSum): 0x8b29344f368b5FA35595325903fE0eAab70C8E1F
Token Name (from contract): Polkamarkets
Token Decimals (from contract): 18
Token Symbol (from contract): POLK
SushiSwap V2 Pair Address of Token: 0x2F3Dc7ECF264EB9f01B4Cd030F1795532B5a9Cf6

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/254
Link to the official homepage of token: https://www.polkamarkets.com/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/polkamarkets/
Link to official Twitter account: https://twitter.com/polkamarkets

**Comment by jiro-ono** [comment]
Added

**Comment by rsmarques** [comment]
@jiro-ono the logo is wrongly shown in SushiSwap on Moonriver:

<img src="https://user-images.githubusercontent.com/4268735/137417728-3a4bb9d5-c92c-4151-8ba6-b40c0419932a.png" width=500>

The correct asset is the one added in https://github.com/sushiswap/assets/blob/master/blockchains/moonriver/assets/0x8b29344f368b5FA35595325903fE0eAab70C8E1F/logo.png
