### ISSUE TITLE
Add {BUCK}: {Arbucks} on {Arbitrum}

### ISSUE THREAD

**Issue by natclark** [sushiswap/default-token-list#277]
- [X] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Arbitrum
Token Address (checkSum): 0xAFD871f684F21Ab9D7137608C71808f83D75e6fc
Token Name (from contract): Arbucks
Token Decimals (from contract): 18
Token Symbol (from contract): BUCK
SushiSwap V2 Pair Address of Token: https://analytics-arbitrum.sushi.com/pairs/0xe3579ed3823846518dc6b51e31360cef6cff189f

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/259
Link to the official homepage of token: https://arbucks.io/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/arbucks/
Link to official Twitter account: https://twitter.com/arbucks_io

**Comment by jiro-ono** [comment]
Added
