### ISSUE TITLE
Add {AXN}: {Axion} on {Polygon}

### ISSUE THREAD

**Issue by Dellybro** [sushiswap/default-token-list#286]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon 
Token Address (checkSum): 0x839F1a22A59eAAf26c85958712aB32F80FEA23d9
Token Name (from contract): Axion
Token Decimals (from contract): 18
Token Symbol (from contract): AXN
SushiSwap V2 Pair Address of Token:   0xf716A43d66C40eE90DF429AF2459E580c1AfC09B

Link to sushiswap/assets PR:
Link to the official homepage of token: https://axion.network/
Link to CoinMarketCap or CoinGecko page of token: 
- https://coinmarketcap.com/currencies/axion/  
- https://www.coingecko.com/en/coins/axion (Not both updated yet, Nomics is)
Link to official Twitter account: https://twitter.com/axion_network

Note: We recently migrated from Ethereum Uniswap to Polygon Sushiswap.

**Comment by Dellybro** [comment]
@jiro-ono since this issue is closed, will we be added to the default token list?

**Comment by jiro-ono** [comment]
@Dellybro yeah, I'm gonna add in a commit coming up in just a second
