### ISSUE TITLE
Add {PHAT}: {Partyhat} on {Arbitrum}

### ISSUE THREAD

**Issue by SerecThunderson** [sushiswap/default-token-list#294]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Arbitrum
Token Address (checkSum): 0x69b2cd28b205b47c8ba427e111dd486f9c461b57
Token Name (from contract): Partyhat
Token Decimals (from contract): 0
Token Symbol (from contract): PHAT
SushiSwap V2 Pair Address of Token: 0x3b2c47fc666122e09dc4afadfe8a3c854ba18c75

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/273
Link to the official homepage of token: https://arbitrum.party 
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/Partyhat_IFT

**Comment by jiro-ono** [comment]
@SerecThunderson You got tx hash for proof of burnt liquidity? Also if you add ssl to the site, maybe spruce it up / get a little more liquidity and I'll add the token to the list

I'll add logo in the meantime though so it shows up on analytics

**Comment by SerecThunderson** [comment]
@jiro-ono Thank you for taking the time to review us.

Below are some links for the burnt liq tx. The scanner shows up bugged for the normal tx page but everything is here.
https://arbiscan.io/tx/0x87002ff1e5b59f42bfe27adc9fdc443fa824ec48580c6125862a4c8d7a77d8ab#eventlog
https://arbiscan.io/token/0x3b2c47fc666122e09dc4afadfe8a3c854ba18c75#balances
https://arbiscan.io/token/0x3b2c47fc666122e09dc4afadfe8a3c854ba18c75?a=0x75365ddb02bc316748fb9a2dc5a33b42f1fba2e7

I'm sorry about the website and understand. The current version was a joke, but it's time we get a real one. I'll get to work on that immediately.

My final question to you is what should our liquidity target be? We started off as a nanotoken - 98% supply against 0.1 ETH and currently have 2.36 ETH in liq. Having a certain goal to hit might be fun for the community.

Thank you very much.
