### ISSUE TITLE
Add NGN: Crypto Nijigen

### ISSUE THREAD

**Issue by lyz52789** [sushiswap/default-token-list#296]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:1
Token Address (checkSum):0x2b5C21578594F7988C7c80D258d0C927C756a848
Token Name (from contract):Crypto Nijigen
Token Decimals (from contract):10
Token Symbol (from contract):NGN
SushiSwap V2 Pair Address of Token:0xDDf479429b7A3ef5382396071be4acC8935cc2aD

Network:137
Token Address (checkSum):0x4C2C04E6f0ec30EbD60b2fFbE11814C3d59910f7
Token Name (from contract):Crypto Nijigen
Token Decimals (from contract):10
Token Symbol (from contract):NGN
SushiSwap V2 Pair Address of Token:0xb257EA9485e02dfA42F15165B97C4C4e118De9b8

Link to sushiswap/assets PR:
Link to the official homepage of token:https://ngn.games/
Link to CoinMarketCap or CoinGecko page of token:https://ipfs.io/ipfs/QmRpUN3B8kXxSNv3Y654pEVM4pJ4SCp8Q92tnTpA6qVkHs
Link to official Twitter account:https://twitter.com/CryptoNijigen

Please contact me if you have other requirements.
It would be great if you can join, thank you very much.

**Comment by jiro-ono** [comment]
Need more liquidity before I can add the token / website seems to be down?
