### ISSUE TITLE
Add {WBB}: {Wrapped Bitblocks} on {Polygon}

### ISSUE THREAD

**Issue by bitblocksxbb** [sushiswap/default-token-list#303]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x4d0b3893009807ec88ec0737c6658f6148597778
Token Name (from contract): Wrapped Bitblocks
Token Decimals (from contract): 8
Token Symbol (from contract): WBB
SushiSwap V2 Pair Address of Token: 0x4d0b3893009807ec88ec0737c6658f6148597778

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/272
Link to the official homepage of token: https://bitblocks.cc
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/bitblockscc

**Comment by jiro-ono** [comment]
Needs liquidity before I can add
