### ISSUE TITLE
Add 1XFL: Flame

### ISSUE THREAD

**Issue by shorinnn** [sushiswap/default-token-list#305]
- [ *] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [ *] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [* ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Harmony
Token Address (checkSum): 0xfd4bf75bd6d61936daa928b169817becaa34982b
Token Name (from contract): Flame
Token Decimals (from contract): 18
Token Symbol (from contract): 1XFL
SushiSwap V2 Pair Address of Token: 0x7c3e7a0404172a4d85f9bf587fbb6dc5c28b54a2

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/287
Link to the official homepage of token: https://flametoken.io/
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/FlameToken

**Comment by jiro-ono** [comment]
Needs some more liquidity before I can add
