### ISSUE TITLE
Add {SCARG}: {Scarred Entertainment} on {Polygon}

### ISSUE THREAD

**Issue by dzuqe** [sushiswap/default-token-list#314]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0x67eD879bf30FED6E1A935970DE1b5850D56F8f46
Token Name (from contract): Scarred Entertainment
Token Decimals (from contract): 18
Token Symbol (from contract): SCARG
SushiSwap V2 Pair Address of Token: 0xe81fe7a71f4466a78a58a830cfbfe122977e46db

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/300
Link to the official homepage of token: https://ipfs.fleek.co/ipfs/QmdBS2TzCkttZUUxvGMEPdHMeYB9CzGGG6EXxpGSS4bZGS/
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/dzuqe

**Comment by jiro-ono** [comment]
Needs some more liquidity before I can add
