### ISSUE TITLE
Add ODAO: ODAO on HARMONY

### ISSUE THREAD

**Issue by Onedao-Finance** [sushiswap/default-token-list#320]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x947394294F75D7502977AC6813FD99f77C2931ec
Token Name (from contract): ODAO
Token Decimals (from contract): 9
Token Symbol (from contract): ODAO
SushiSwap V2 Pair Address of Token: 0x4f658217f163509115b6e1fbba37cd9aefbdba12, 0x171ff11b53674958c273bcfccbc731aa6cae96f8, 0x34f21378a6fc29acc1eacb82bc5f7dec794ce537

Link to sushiswap/assets PR: sushiswap/assets#294
Link to the official homepage of token: https://onedao.finance/
Link to CoinMarketCap or CoinGecko page of token: 
- https://coinmarketcap.com/currencies/onedao-finance/
- https://www.coingecko.com/en/coins/onedao-finance
Link to official Twitter account: https://twitter.com/onedao_finance

**Comment by jiro-ono** [comment]
Added
