### ISSUE TITLE
Add {USV}: {Universal Store of Value} on {Polygon}

### ISSUE THREAD

**Issue by atlascreator** [sushiswap/default-token-list#323]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0xAC63686230f64BDEAF086Fe6764085453ab3023F
Token Name (from contract): Universal Store of Value
Token Decimals (from contract): 9
Token Symbol (from contract): USV
SushiSwap V2 Pair Address of Token: 0xc16e382aa7353aad0f598856afd9a93513542970

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/311
Link to the official homepage of token: https://www.atlasusv.com
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/atlasusv

**Comment by jiro-ono** [comment]
Added to the list
