### ISSUE TITLE
Add $ALPHA: (AlphaToken) on Ethereum Mainnet

### ISSUE THREAD

**Issue by Melvinmcrn** [sushiswap/default-token-list#326]
- [X] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum Mainnet
Token Address (checkSum): 0xa1faa113cbE53436Df28FF0aEe54275c13B40975
Token Name (from contract): AlphaToken
Token Decimals (from contract): 18
Token Symbol (from contract): ALPHA
SushiSwap V2 Pair Address of Token: 0xf55C33D94150d93c2cfb833bcCA30bE388b14964

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/312
Link to the official homepage of token: https://alphafinance.io/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/alpha-finance-lab/
Link to official Twitter account: https://twitter.com/AlphaFinanceLab

**Comment by jiro-ono** [comment]
We already got this one added
