### ISSUE TITLE
Add {DAT}: {DigiArt Token}

### ISSUE THREAD

**Issue by pixobits** [sushiswap/default-token-list#329]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0xD7d9e6Ed2762B3403534d7152018686f3d03c4F6
Token Name (from contract): DigiArt Token
Token Decimals (from contract): 9
Token Symbol (from contract): DAT
SushiSwap V2 Pair Address of Token: 0x33732413d6DeCa749840733D87EE3a30D0B1d42B

Link to sushiswap/assets PR:
Link to the official homepage of token: https://digiart.city
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/pixobitsnft

**Comment by jiro-ono** [comment]
What network is this on? And can you submit a PR with the logo to the github.com/sushiswap/assets repo?

**Comment by pixobits** [comment]
Binance Smart Chain
I've already done that and waiting approval
https://github.com/sushiswap/assets/pull/315
Thanks.

**Comment by pixobits** [comment]
should I do something else?
