### ISSUE TITLE
Add SAND: SAND

### ISSUE THREAD

**Issue by mvanmeerbeck** [sushiswap/default-token-list#330]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): [0xBbba073C31bF03b8ACf7c28EF0738DeCF3695683](https://polygonscan.com/token/0xBbba073C31bF03b8ACf7c28EF0738DeCF3695683)
Token Name (from contract): SAND
Token Decimals (from contract): 18
Token Symbol (from contract): SAND
SushiSwap V2 Pair Address of Token: [0x1fc05157e66300377b637e93262b355d405f71c6](https://polygonscan.com/token/0x1fc05157e66300377b637e93262b355d405f71c6)

Link to sushiswap/assets PR: https://github.com/sushiswap/default-token-list/pull/331
Link to the official homepage of token: https://www.sandbox.game/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/the-sandbox/
Link to official Twitter account: https://twitter.com/TheSandboxGame

**Comment by jiro-ono** [comment]
Should be added already
