### ISSUE TITLE
Add {CPRX}: {Crypto Perx} on {Ethereum}

### ISSUE THREAD

**Issue by alexis-cprx** [sushiswap/default-token-list#333]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0xc6e145421fd494b26dcf2bfeb1b02b7c5721978f
Token Name (from contract): Crypto Perx
Token Decimals (from contract): 18
Token Symbol (from contract): CPRX
SushiSwap V2 Pair Address of Token: 

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/316
Link to the official homepage of token: https://www.cryptoperx.com/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/fr/currencies/crypto-perx/
Link to official Twitter account: https://twitter.com/cryptoperxCH

**Comment by jiro-ono** [comment]
Adding in another commit
