### ISSUE TITLE
Add {USV}: {Universal Store of Value} on {Ethereum}

### ISSUE THREAD

**Issue by atlascreator** [sushiswap/default-token-list#334]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x88536C9B2C4701b8dB824e6A16829D5B5Eb84440
Token Name (from contract): Universal Store of Value
Token Decimals (from contract): 9
Token Symbol (from contract): USV
SushiSwap V2 Pair Address of Token: 0xcb8e690062050617c5921a0da7df30a1a72d76fe

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/317
Link to the official homepage of token: https://www.atlasusv.com
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/atlasusv

**Comment by jiro-ono** [comment]
Added

**Comment by atlascreator** [comment]
@jiro-ono the token logo is missing due to this still needs to be merged: https://github.com/sushiswap/assets/pull/317

**Comment by atlascreator** [comment]
@jiro-ono any update here? Token logo is still missing on site. Please merge https://github.com/sushiswap/assets/pull/317 Thank you.
