### ISSUE TITLE
Add FLUX: Flux Protocol on Arbitrum

### ISSUE THREAD

**Issue by jhd2best** [sushiswap/default-token-list#335]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Arbitrum
Token Address (checkSum): 0x2338a5d62e9a766289934e8d2e83a443e8065b83
Token Name (from contract): Flux Protocol
Token Decimals (from contract): 18
Token Symbol (from contract): FLUX
SushiSwap V2 Pair Address of Token: https://analytics-arbitrum.sushi.com/pairs/0xdf2fc71e11462ea12088856c282e720793698781

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/278 (already added and closed)
Link to the official homepage of token: https://official.flux.01.finance
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/flux-protocol
Link to official Twitter account: https://twitter.com/zero1_flux

**Comment by jhd2best** [comment]
@jiro-ono please help deal with it. thanks

**Comment by matthewlilley** [comment]
merged
