### ISSUE TITLE
Add {OpenX}: {OpenSwap}

### ISSUE THREAD

**Issue by luciocc55** [sushiswap/default-token-list#338]
- [ x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x ] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Harmony  (1666600000)
Token Address (checkSum):0x01A4b054110d57069c1658AFBC46730529A3E326
Token Name (from contract):OpenSwap
Token Decimals (from contract):18
Token Symbol (from contract):OpenX
SushiSwap V2 Pair Address of Token: We dont have a pair with sushi.

Link to sushiswap/assets PR:https://github.com/sushiswap/default-token-list/pull/337
Link to the official homepage of token:https://app.openswap.one/
Link to CoinMarketCap or CoinGecko page of token:  (Waiting on listing)
Link to official Twitter account:https://twitter.com/OpenSwap_one/

**Comment by jiro-ono** [comment]
Added
