### ISSUE TITLE
Add EMT: Emanate

### ISSUE THREAD

**Issue by blakecannell** [sushiswap/default-token-list#339]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x893700a1a86ee68b92536bf6fd4d3200d7369f7d
Token Name (from contract): Emanate
Token Decimals (from contract): 18
Token Symbol (from contract): EMT
SushiSwap V2 Pair Address of Token: 0x7ea57883d95D470967808ADC230194A78780BDFD

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/321
Link to the official homepage of token: https://emanate.live/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/emanate/
Link to official Twitter account: https://twitter.com/EmanateOfficial

**Comment by blakecannell** [comment]
Updated with correct LP address.

**Comment by jiro-ono** [comment]
Added
