### ISSUE TITLE
Add MODA: moda

### ISSUE THREAD

**Issue by blakecannell** [sushiswap/default-token-list#340]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x1117ac6ad6cdf1a3bc543bad3b133724620522d5
Token Name (from contract): moda
Token Decimals (from contract): 18
Token Symbol (from contract): MODA
SushiSwap V2 Pair Address of Token: 0x1c934bc86839b5718a1bdf69880de56f65388531

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/322
Link to the official homepage of token: https://www.modadao.io/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/moda-dao/
Link to official Twitter account: https://twitter.com/MODA_DAO

**Comment by jiro-ono** [comment]
Added
