### ISSUE TITLE
Add VOXEL: VOXEL Token

### ISSUE THREAD

**Issue by MiningBurn** [sushiswap/default-token-list#344]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0xd0258a3fd00f38aa8090dfee343f10a9d4d30d3f
Token Name (from contract): VOXEL Token
Token Decimals (from contract): 18
Token Symbol (from contract): VOXEL
SushiSwap V2 Pair Address of Token: 0xd134c7785866f1bf800c2955b200c3b0efcd3f50

Link to sushiswap/assets PR:
Link to the official homepage of token: https://Voxies.com
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/voxies/
Link to official Twitter account: https://twitter.com/VoxiesNFT

**Comment by jiro-ono** [comment]
Added
