### ISSUE TITLE
Add ARBIS: ARBIS

### ISSUE THREAD

**Issue by 0xPuffin** [sushiswap/default-token-list#345]
- [ ✔] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [ ✔] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [ ✔] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x9f20de1fc9b161b34089cbEAE888168B44b03461
Token Name (from contract): ARBIS | We have the yields
Token Decimals (from contract): 18
Token Symbol (from contract): ARBIS
SushiSwap V2 Pair Address of Token:  0xa32329952C857Fbc707B4d2AD5901dDB93bfeF9F

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/325
Link to the official homepage of token: https://arbis.finance
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/arbis-finance
Link to official Twitter account: https://twitter.com/arbis_finance

**Comment by jiro-ono** [comment]
Added

**Comment by 0xPuffin** [comment]
thank you
