### ISSUE TITLE
Add MSU: MetaSoccer Universe

### ISSUE THREAD

**Issue by dmilla** [sushiswap/default-token-list#346]
- [X] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0xe8377A076adAbb3F9838afB77Bee96Eac101ffB1
Token Name (from contract): MetaSoccer Universe
Token Decimals (from contract): 18
Token Symbol (from contract): MSU
SushiSwap V2 Pair Address of Token: https://analytics-polygon.sushi.com/pairs/0xD10bB4ED281A84492343573885168027Cc625bf7

Link to sushiswap/assets PR:
Link to the official homepage of token: https://metasoccer.com/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/metasoccer/
Link to official Twitter account: https://twitter.com/MetaSoccer_EN

**Comment by jiro-ono** [comment]
Added
