### ISSUE TITLE
Add stONE: Staked ONE (from Tranquil Finance)

### ISSUE THREAD

**Issue by 0xYamcha** [sushiswap/default-token-list#348]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x22d62b19b7039333ad773b7185bb61294f3adc19
Token Name (from contract): Staked One
Token Decimals (from contract): 18
Token Symbol (from contract): stONE
SushiSwap V2 Pair Address of Token: 0x6b53ca1ed597ed7ccd5664ec9e03329992c2ba87

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/327
Link to the official homepage of token: https://tranquil.finance
Link to CoinMarketCap or CoinGecko page of token: TBD
Link to official Twitter account: @tranquil_fi

**Comment by jiro-ono** [comment]
Added
