### ISSUE TITLE
Add ALGB: Algebra on Polygon

### ISSUE THREAD

**Issue by lilchizh** [sushiswap/default-token-list#351]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0x0169ec1f8f639b32eec6d923e24c2a2ff45b9dd6
Token Name (from contract): Algebra
Token Decimals (from contract): 18
Token Symbol (from contract): ALGB
SushiSwap V2 Pair Address of Token: 0x609602abe648b1c81e4444c7ca9ffe90d89c7b77

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/331
Link to the official homepage of token: https://algebra.finance
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/algebra
Link to official Twitter account: https://twitter.com/CryptoAlgebra

**Comment by jiro-ono** [comment]
Added
