### ISSUE TITLE
Add CERBY: Cerby Token

### ISSUE THREAD

**Issue by CerbyToken** [sushiswap/default-token-list#354]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0xdef1fac7Bf08f173D286BbBDcBeeADe695129840
Token Name (from contract): Cerby Token
Token Decimals (from contract): 18
Token Symbol (from contract): CERBY
SushiSwap V2 Pair Address of Token: 0x4b63d5aaf3fda1bfc82d5304d0be88264d1957df

Network: BSC
Token Address (checkSum): 0xdef1fac7Bf08f173D286BbBDcBeeADe695129840
Token Name (from contract): Cerby Token
Token Decimals (from contract): 18
Token Symbol (from contract): CERBY
SushiSwap V2 Pair Address of Token: 0xbf3e1f80636124807df48a059c4ace3496c8c427

Network: Polygon
Token Address (checkSum): 0xdef1fac7Bf08f173D286BbBDcBeeADe695129840
Token Name (from contract): Cerby Token
Token Decimals (from contract): 18
Token Symbol (from contract): CERBY
SushiSwap V2 Pair Address of Token: 0x2cb1a360467b16152585e4652dff0d13653bfbec

Network: Avalanche
Token Address (checkSum): 0xdef1fac7Bf08f173D286BbBDcBeeADe695129840
Token Name (from contract): Cerby Token
Token Decimals (from contract): 18
Token Symbol (from contract): CERBY
SushiSwap V2 Pair Address of Token: 0x5ecfca21f29366ab9e8e1f2c7de56cdb96037c21

Network: Fantom
Token Address (checkSum): 0xdef1fac7Bf08f173D286BbBDcBeeADe695129840
Token Name (from contract): Cerby Token
Token Decimals (from contract): 18
Token Symbol (from contract): CERBY
SushiSwap V2 Pair Address of Token: 0x099754f983082a69fba83eddad6c375c524a185b

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/334
Link to the official homepage of token: https://cerby.fi
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/cerby-token
Link to official Twitter account: https://twitter.com/CerbyToken

**Comment by jiro-ono** [comment]
Added
