### ISSUE TITLE
Add cLA: CeloLaunch on Celo

### ISSUE THREAD

**Issue by CeloLaunch** [sushiswap/default-token-list#360]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Celo
Token Address (checkSum): 0x5927fd244E11dB1c7b1215619144d2aAbAc80a4F
Token Name (from contract): CeloLaunch
Token Decimals (from contract): 18
Token Symbol (from contract): cLA
SushiSwap V2 Pair Address of Token: 0xe7fde327d35ad6014d249acdea3b827a81bd9965

Link to sushiswap/assets PR: [https://github.com/sushiswap/assets/pull/338](https://github.com/sushiswap/assets/pull/338)
Link to the official homepage of token: [https://celolaunch.io/](https://celolaunch.io)
Link to CoinMarketCap or CoinGecko page of token: [https://coinmarketcap.com/currencies/celolaunch](https://coinmarketcap.com/currencies/celolaunch)
Link to official Twitter account: [https://twitter.com/celolaunch](https://twitter.com/celolaunch)

**Comment by jiro-ono** [comment]
Added
