### ISSUE TITLE
Add WOWX: WowneroX

### ISSUE THREAD

**Issue by wownerox** [sushiswap/default-token-list#361]
- [ x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x ] I will not ping the Discord about this listing request.

Network: Avalanche
Token Address (checkSum): `0xbA5dC7e77d150816b758E9826fCad2D74820e379`
Token Name (from contract): WowneroX
Token Decimals (from contract): 18
Token Symbol (from contract): WOWX

Link to sushiswap/assets PR:
Link to the official homepage of token: https://wownero.org
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/wownero/
Link to official Twitter account: https://twitter.com/W0wn3r0

**Comment by jiro-ono** [comment]
needs liqudidi
