### ISSUE TITLE
Add TUT: Tutellus token

### ISSUE THREAD

**Issue by victormer** [sushiswap/default-token-list#362]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon (PoS)
Token Address (checkSum): 0x12a34A6759c871C4C1E8A0A42CFc97e4D7Aaf68d
Token Name (from contract): Tutellus token
Token Decimals (from contract): 18
Token Symbol (from contract): TUT
SushiSwap V2 Pair Address of Token: 0x5d9AC8993B714df01D079d1B5b0b592e579Ca099, 0x5A4f99061EF77b8Fc7195CE914fB588388526388, 0xc1aacD07038c17fa878DfEd571f6b66218F96dD8

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/339
Link to the official homepage of token: https://www.tutellus.io/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/tutellus/ , https://www.coingecko.com/en/coins/tutellus
Link to official Twitter account: https://twitter.com/tutellus

**Comment by jiro-ono** [comment]
Added

**Comment by victormer** [comment]
@jiro-ono Not added in Sushi interface yet I see. Is there any step ahead before it to be there? Thanks!
