### ISSUE TITLE
Add GMI: Bankless DeFi Innovation Index

### ISSUE THREAD

**Issue by asharma13524** [sushiswap/default-token-list#363]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x47110d43175f7f2C2425E7d15792acC5817EB44f
Token Name (from contract): Bankless DeFi Innovation Index
Token Decimals (from contract): 18
Token Symbol (from contract): GMI

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/340
Link to the official homepage of token: https://indexcoop.com/
Link to official Twitter account: https://twitter.com/indexcoop

**Comment by jiro-ono** [comment]
Added
