### ISSUE TITLE
Add CHEEZ: Cheese on Harmony ONE

### ISSUE THREAD

**Issue by rshtirmer** [sushiswap/default-token-list#366]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Harmony
Token Address (checkSum): 0xBbD83eF0c9D347C85e60F1b5D2c58796dBE1bA0d
Token Name (from contract): Cheese
Token Decimals (from contract): 9 
Token Symbol (from contract): CHEEZ
SushiSwap V2 Pair Address of Token:

Link to sushiswap/assets PR: [pull/365](https://github.com/sushiswap/default-token-list/pull/365)
Link to the official homepage of token: https://www.cheese.game
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/cheesedao
Link to official Twitter account: https://twitter.com/CheezDAO

**Comment by jiro-ono** [comment]
Added
