### ISSUE TITLE
Add X: X

### ISSUE THREAD

**Issue by anthony-xxyz** [sushiswap/default-token-list#367]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0x7f3141c4D6b047fb930991b450f1eD996a51CB26
Token Name (from contract): X
Token Decimals (from contract): 18
Token Symbol (from contract): X
SushiSwap V2 Pair Address of Token: 0xc2Ce29Af8930fc32Ca24ccB76C2866fB2Bf692fE

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/342
Link to the official homepage of token: http://x.xyz/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/x/
Link to official Twitter account: https://twitter.com/xdotxyz

**Comment by jiro-ono** [comment]
Added
