### ISSUE TITLE
Add HND: Hundred Finance on ethereum, arbitrum, fantom, harmony

### ISSUE THREAD

**Issue by nipa85** [sushiswap/default-token-list#368]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0x10010078a54396F62c96dF8532dc2B4847d47ED3
Token Name (from contract): Hundred Finance
Token Decimals (from contract): 18
Token Symbol (from contract): HND
SushiSwap V2 Pair Address of Token: 

Network: Arbitrum
Token Address (checkSum): 0x10010078a54396F62c96dF8532dc2B4847d47ED3
Token Name (from contract): Hundred Finance
Token Decimals (from contract): 18
Token Symbol (from contract): HND
SushiSwap V2 Pair Address of Token: 

Network: Fantom
Token Address (checkSum): 0x10010078a54396F62c96dF8532dc2B4847d47ED3
Token Name (from contract): Hundred Finance
Token Decimals (from contract): 18
Token Symbol (from contract): HND
SushiSwap V2 Pair Address of Token: 

Network: Harmony
Token Address (checkSum): 0x10010078a54396F62c96dF8532dc2B4847d47ED3
Token Name (from contract): Hundred Finance
Token Decimals (from contract): 18
Token Symbol (from contract): HND
SushiSwap V2 Pair Address of Token: 0x008cebc4bbf13145dbb34b542d6f3b7b01e1e040

Link to sushiswap/assets PR: [pull/344](https://github.com/sushiswap/assets/pull/344)
Link to the official homepage of token:  [Hundred Finance](https://hundred.finance)
Link to CoinMarketCap or CoinGecko page of token:  [https://www.coingecko.com/en/coins/hundred-finance](https://www.coingecko.com/en/coins/hundred-finance)
Link to official Twitter account: [https://twitter.com/HundredFinance](https://twitter.com/HundredFinance)

**Comment by jiro-ono** [comment]
Added
