### ISSUE TITLE
Add {LYRA}: {Lyra}

### ISSUE THREAD

**Issue by mjs-12** [sushiswap/default-token-list#372]
- [X] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0x01BA67AAC7f75f647D94220Cc98FB30FCc5105Bf
Token Name (from contract): Lyra Token
Token Decimals (from contract): 18
Token Symbol (from contract): LYRA
SushiSwap V2 Pair Address of Token: 0x52DaC05FC0000e9F01CE9A1E91592BfbFcE87350

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/345
Link to the official homepage of token: https://www.lyra.finance/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/lyra-finance
Link to official Twitter account: https://twitter.com/lyrafinance

**Comment by jiro-ono** [comment]
Added
