### ISSUE TITLE
Add {CLNY}: {MARSCOLONY}

### ISSUE THREAD

**Issue by EugeneFinch** [sushiswap/default-token-list#373]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x0d625029e21540abdfafa3bfc6fd44fb4e0a66d0
Token Name (from contract): ColonyToken
Token Decimals (from contract): 18
Token Symbol (from contract): CLNY
SushiSwap V2 Pair Address of Token:  0xcd818813f038a4d1a27c84d24d74bbc21551fa83 

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/346
Link to the official homepage of token: https://marscolony.io/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/search_redirect?id=marscolony&type=coin
Link to official Twitter account: https://twitter.com/marscolonyio

**Comment by jiro-ono** [comment]
Added
