### ISSUE TITLE
Add {AX}: {AthleteX}

### ISSUE THREAD

**Issue by user2745** [sushiswap/default-token-list#374]
- [  ] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [  ] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [  ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: **Polygon**
Token Address (checkSum): 0x5617604ba0a30e0ff1d2163ab94e50d8b6d0b0df
Token Name (from contract): AthleteX
Token Decimals (from contract): 18
Token Symbol (from contract): AX
SushiSwap V2 Pair Address of Token: (AX-WETH) 0x03e0f3f693fa52fabdbfa8c2e641d6395e96ec5b
Link to sushiswap/assets PR: [PR Link](https://github.com/sushiswap/assets/pull/347)
Link to the official homepage of token: [AthleteX Homepage](https://www.athletex.io)
Link to CoinMarketCap or CoinGecko page of token: [Coingecko Page](coingecko.com/en/coins/athletex)
Link to official Twitter account: [AthleteX Twitter](http://twitter.com/athletex_dao)

**Comment by jiro-ono** [comment]
Added

**Comment by user2745** [comment]
Thank you
