### ISSUE TITLE
Add {ELK}: {Elk}

### ISSUE THREAD

**Issue by LtSnakePlissken** [sushiswap/default-token-list#375]
- [ x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [ x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Fuse
Token Address (checkSum): 0xE1C110E1B1b4A1deD0cAf3E42BfBdbB7b5d7cE1C 
Token Name (from contract): Elk
Token Decimals (from contract): 18
Token Symbol (from contract): ELK
SushiSwap V2 Pair Address of Token: 0x3f7bfed4bEc4C7caa48e6863742d85cb65873B17

Link to sushiswap/assets PR:  https://docs.elk.finance/brand-assets
Link to the official homepage of token: https://elk.finance/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/elk-finance/
Link to official Twitter account: https://twitter.com/elk_finance

**Comment by jiro-ono** [comment]
Added
