### ISSUE TITLE
Add CMK: Credmark

### ISSUE THREAD

**Issue by v1nvn** [sushiswap/default-token-list#376]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0x68CFb82Eacb9f198d508B514d898a403c449533E
Token Name (from contract): Credmark
Token Decimals (from contract): 18
Token Symbol (from contract): CMK
SushiSwap V2 Pair Address of Token: 0x3349217670f9aa55c5640a2b3d806654d27d0569 (CMK-WETH)

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/348
Link to the official homepage of token: https://credmark.com/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/credmark
Link to official Twitter account: https://twitter.com/credmarkhq

**Comment by jiro-ono** [comment]
Added
