### ISSUE TITLE
Add CBD: CybeeDAO on Ethereum

### ISSUE THREAD

**Issue by tracy-e** [sushiswap/default-token-list#378]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum
Token Address (checkSum): 0x9B812C65529eC7d20ab630235ae20fde022c8aD3
Token Name (from contract): CybeeDAO
Token Decimals (from contract): 18
Token Symbol (from contract): CBD
SushiSwap V2 Pair Address of Token: [0x5b8C5692F565fC067F5598AbD866fb2Ca17493B4](https://analytics.sushi.com/pairs/0x5b8C5692F565fC067F5598AbD866fb2Ca17493B4)

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/349
Link to the official homepage of token: https://cybee.xyz
Link to CoinMarketCap or CoinGecko page of token:  Pending
Link to official Twitter account: https://twitter.com/cybeeMiniverse

**Comment by jiro-ono** [comment]
needs liquidity
