### ISSUE TITLE
Add CREDA: CreDA Protocol Token

### ISSUE THREAD

**Issue by Kelvinorin** [sushiswap/default-token-list#380]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Arbitrum
Token Address (checkSum): 0xc136E6B376a9946B156db1ED3A34b08AFdAeD76d
Token Name (from contract): CreDA Protocol Token
Token Decimals (from contract): 18
Token Symbol (from contract): CREDA
SushiSwap V2 Pair Address of Token: 0x2F73FB16933585Ba089100C05561D58FD342bDf5

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/350
Link to the official homepage of token: https://creda.app
Link to CoinMarketCap or CoinGecko page of token: https://coingecko.com/en/coins/creda
Link to official Twitter account: https://twitter.com/CreDAfinance

**Comment by jiro-ono** [comment]
Added
