### ISSUE TITLE
Add TEM: Templar Token

### ISSUE THREAD

**Issue by TemplarDAO** [sushiswap/default-token-list#386]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

Please provide the following information for your token.

Network: Harmony
Token Address (checkSum): 0xd754ae7bb55fEB0c4BA6bC037b4A140f14ebE018
Token Name (from contract): Templar Token
Token Decimals (from contract): 9
Token Symbol (from contract): TEM
SushiSwap V2 Pair Address of Token: 0xeed838406194feba1bd654cfdf85a941ac0944bc

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/357
Link to the official homepage of token: https://templar.finance
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/templardao/
https://www.coingecko.com/en/coins/templar-dao
Link to official Twitter account: https://twitter.com/TemplarDAO

**Comment by jiro-ono** [comment]
Added
