### ISSUE TITLE
Add RAIDER: Crypto Raiders

### ISSUE THREAD

**Issue by Nateliason** [sushiswap/default-token-list#387]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0xcd7361ac3307D1C5a46b63086a90742Ff44c63B3
Token Name (from contract): Crypto Raiders
Token Decimals (from contract): 18
Token Symbol (from contract): RAIDER
SushiSwap V2 Pair Address of Token: 0x2e7d6490526c7d7e2fdea5c6ec4b0d1b9f8b25b7 and 0x426a56f6923c2b8a488407fc1b38007317ecafb1

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/358
Link to the official homepage of token: https://cryptoraiders.xyz
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/crypto-raiders
Link to official Twitter account: https://twitter.com/crypto_raiders

**Comment by jiro-ono** [comment]
Added
