### ISSUE TITLE
Add AURUM: Raider Aurum

### ISSUE THREAD

**Issue by Nateliason** [sushiswap/default-token-list#388]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0x34d4ab47Bee066F361fA52d792e69AC7bD05ee23
Token Name (from contract): Raider Aurum
Token Decimals (from contract): 18
Token Symbol (from contract): AURUM
SushiSwap V2 Pair Address of Token: 0x91670a2a69554c61d814cd7f406d7793387e68ef and 0xabee7668a96c49d27886d1a8914a54a5f9805041

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/358
Link to the official homepage of token: https://cryptoraiders.xyz/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/raider-aurum
Link to official Twitter account: https://twitter.com/crypto_raiders

**Comment by jiro-ono** [comment]
Added, sorry bout that long wait on this one
