### ISSUE TITLE
Add GURU: Guru on Polygon

### ISSUE THREAD

**Issue by Yama-NidhiDAO** [sushiswap/default-token-list#389]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0x057E0bd9B797f9Eeeb8307B35DbC8c12E534c41E
Token Name (from contract): Guru
Token Decimals (from contract): 9
Token Symbol (from contract): GURU
SushiSwap V2 Pair Address of Token: 0x7c9B16d845FE163F464d265193cC2B4eE3faC326

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/360
Link to the official homepage of token: https://nidhidao.finance
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/nidhi-dao
Link to official Twitter account: https://twitter.com/NidhiDAO

**Comment by jiro-ono** [comment]
Added
