### ISSUE TITLE
Add UMAMI: Umami on Arbitrum

### ISSUE THREAD

**Issue by keepsense** [sushiswap/default-token-list#391]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x1622bf67e6e5747b81866fe0b85178a93c7f86e3
Token Name (from contract): Umami
Token Decimals (from contract): 9
Token Symbol (from contract): UMAMI
SushiSwap V2 Pair Address of Token: https://app.sushi.com/analytics/pairs/0xebfc40b1ac6907673b33ddc370f868dc21cd5b2b

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/362
Link to the official homepage of token: https://app.umami.finance/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/umami-finance
Link to official Twitter account: https://twitter.com/UmamiFinance

**Comment by jiro-ono** [comment]
Added
