### ISSUE TITLE
Add CIG: Cigarette Token on Ethereum

### ISSUE THREAD

**Issue by 0xTycoon** [sushiswap/default-token-list#393]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Ethereum mainnet
Token Address (checkSum): 0xCB56b52316041A62B6b5D0583DcE4A8AE7a3C629
Token Name (from contract): Cigarette Token
Token Decimals (from contract): 18
Token Symbol (from contract): CIG
SushiSwap V2 Pair Address of Token: 0x22b15c7Ee1186A7C7CFfB2D942e20Fc228F6E4Ed

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/363
Link to the official homepage of token: https://cigtoken.eth.limo/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/cigarette-token
Link to official Twitter account: https://twitter.com/CigToken

**Comment by jiro-ono** [comment]
Added
