### ISSUE TITLE
Add {LICP}: {Liquid ICP}

### ISSUE THREAD

**Issue by Soolking-cyber** [sushiswap/default-token-list#397]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Matic Mainnet

Token Address (checkSum): 0x1b43b97094aa3c6cc678edb9e28ac67daaa7cc64
Token Name (from contract): Liquid ICP
Token Decimals (from contract): 18
Token Symbol (from contract): LICP
SushiSwap V2 Pair Address of Token: 0x47ee7e6a997ba0d1b02b1de786a6324f8e8cef20, 0x32340eb37cd354b24fd7a1ed654ae2dfd22805e7

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/369
Link to the official homepage of token: https://www.icp-20.com/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/liquid-icp/
Link to official Twitter account: https://twitter.com/LiquidICP

**Comment by jiro-ono** [comment]
Added
