### ISSUE TITLE
Add $POP: POPCORN NETWORK

### ISSUE THREAD

**Issue by mefuru** [sushiswap/default-token-list#399]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0xc5b57e9a1e7914fda753a88f24e5703e617ee50c
Token Name (from contract): Popcorn
Token Decimals (from contract): 18
Token Symbol (from contract): POP
SushiSwap V2 Pair Address of Token: 0xc5b57e9a1e7914fda753a88f24e5703e617ee50c

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/371
Link to the official homepage of token: https://popcorn.network/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/popcorn-network/
Link to official Twitter account: https://twitter.com/Popcorn_DAO

**Comment by jiro-ono** [comment]
Added
