### ISSUE TITLE
Add {ZPAE}: {ZelaaPayAE}

### ISSUE THREAD

**Issue by thezelaapayae** [sushiswap/default-token-list#410]
- [Yes] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [Yes ] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [Yes ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0xC35De09873D366EEe607a975903b49AB8dE7B90C
Token Name (from contract): ZelaaPayAE
Token Decimals (from contract): 9
Token Symbol (from contract): ZPAE
SushiSwap V2 Pair Address of Token: https://app.sushi.com/analytics/pairs/0x3e9f6641302000a5ac8c65a71163573d97f27023

Link to sushiswap/assets PR:  https://github.com/trustwallet/assets/pull/18001
Link to the official homepage of token: https://www.zelaapay.ae/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/zelaapayae/
Link to official Twitter account: https://www.twitter.com/zelaapay

**Comment by jiro-ono** [comment]
needs liquidity
