### ISSUE TITLE
Add cMeta: MetaCelo on Celo

### ISSUE THREAD

**Issue by MetaCelo** [sushiswap/default-token-list#424]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Celo
Token Address (checkSum): 0xF3608F846cA73147F08FdE8D57f45E27CeEA4d61
Token Name (from contract): MetaCelo
Token Decimals (from contract): 18
Token Symbol (from contract): cMeta
SushiSwap V2 Pair Address of Token: 0x25b2cfe40157347d64bfc043ec7ae3e357e6bee3

Link to sushiswap/assets PR: [sushiswap/assets#373](https://github.com/sushiswap/assets/pull/373)
Link to the official homepage of token: [https://metacelo.io/](https://metacelo.io/)
Link to CoinMarketCap or CoinGecko page of token: [https://coinmarketcap.com/currencies/metacelo](https://coinmarketcap.com/currencies/metacelo)
Link to official Twitter account: [https://twitter.com/Meta_Celo](https://twitter.com/Meta_Celo)

**Comment by jiro-ono** [comment]
Added
