### ISSUE TITLE
Add {XBBX}: {BitblocksDAO}

### ISSUE THREAD

**Issue by BitblocksDAO** [sushiswap/default-token-list#425]
- [ ✅] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [✅ ] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [✅ ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0xec79b78bcedf3c4b6d12c27ba6d092ad178b5b30
Token Name (from contract): BitblocksDAO
Token Decimals (from contract): 18
Token Symbol (from contract): XBBX
SushiSwap V2 Pair Address of Token: https://app.sushi.com/analytics/pairs/0x15328dec67b2d9c90845fb2b789c8498a9d8ec46

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/375
Link to the official homepage of token: https://bitblocksdao.org
Link to CoinMarketCap or CoinGecko page of token: 
Link to official Twitter account: https://twitter.com/bitblocksdao

**Comment by jiro-ono** [comment]
needs some liquidity

**Comment by BitblocksDAO** [comment]
> needs some liquidity

How much liquidity in needed? Thanks.
