### ISSUE TITLE
UMAMI token added with 18 decimals instead of 9

### ISSUE THREAD

**Issue by keepsense** [sushiswap/default-token-list#427]
Hi @jiro-ono ,

The request for this token was for 9 decimals, however the commit added it with 18. See commit, below:

https://github.com/sushiswap/default-token-list/commit/e7aaf5fb373d5d60f21d816990bfedd8ba324260

Can this please be updated to reflect 9 decimals?

Thank you!

Added

_Originally posted by @jiro-ono in https://github.com/sushiswap/default-token-list/issues/391#issuecomment-1039698212_

**Comment by jiro-ono** [comment]
Should be fixed now

**Comment by keepsense** [comment]
Thanks, @jiro-ono !
