### ISSUE TITLE
Add SOURCE: Source

### ISSUE THREAD

**Issue by Bridgerz** [sushiswap/default-token-list#428]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Celo
Token Address (checkSum): 0x74c0C58B99b68cF16A717279AC2d056A34ba2bFe
Token Name (from contract): Source
Token Decimals (from contract):18
Token Symbol (from contract): SOURCE

Network: Ethereum
Token Address (checkSum): 0x7118057ff0F4Fd0994fb9d2D94de8231d5cca79E
Token Name (from contract): Source
Token Decimals (from contract): 18
Token Symbol (from contract):SOURCE

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/376
Link to the official homepage of token: https://resource.finance/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/resource-protocol/
Link to official Twitter account: https://twitter.com/ReSource_Fi

**Comment by Tooktoin** [comment]
Okay

**Comment by jiro-ono** [comment]
Added
