### ISSUE TITLE
Add RIC:RIC

### ISSUE THREAD

**Issue by mindsgn** [sushiswap/default-token-list#429]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0x263026E7e53DBFDce5ae55Ade22493f828922965
Token Name (from contract): RIC
Token Decimals (from contract): 18
Token Symbol (from contract): RIC
SushiSwap V2 Pair Address of Token: 

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/379
Link to the official homepage of token: https://ricochet.exchange/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/ricochet
Link to official Twitter account: https://twitter.com/ricochetxchange

**Comment by jiro-ono** [comment]
Added
