### ISSUE TITLE
Add MPS:Mt Pelerin Shares on GnosisChain

### ISSUE THREAD

**Issue by Sigri44** [sushiswap/default-token-list#438]
- [X] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: GnosisChain
Token Address (checkSum): 0xfa57AA7beED63D03Aaf85fFd1753f5f6242588fb
Token Name (from contract): MtPelerin Shares
Token Decimals (from contract): 0
Token Symbol (from contract): MPS
SushiSwap V2 Pair Address of Token: 0x78E87757861185Ec5e8C0EF6BF0C69Fa7832df6C

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/383
Link to the official homepage of token: https://www.mtpelerin.com/shareholders
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/mt-pelerin-shares
Link to official Twitter account: https://twitter.com/mtpelerin

**Comment by jiro-ono** [comment]
Added
