### ISSUE TITLE
Add XGEM: Exchange Genesis Ethlas Medium

### ISSUE THREAD

**Issue by raynerljm** [sushiswap/default-token-list#441]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Polygon
Token Address (checkSum): 0x02649c1ff4296038de4b9ba8f491b42b940a8252
Token Name (from contract): Exchange Genesis Ethlas Medium
Token Decimals (from contract): 18
Token Symbol (from contract): XGEM
SushiSwap V2 Pair Address of Token: 0xffc654a0d0f740748d9d4d0061c96c284c3cdf88

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/385
Link to the official homepage of token: https://ethlas.com/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/exchange-genesis-ethlas-medium
Link to official Twitter account: https://twitter.com/Ethlas_Official

**Comment by jiro-ono** [comment]
Added
