### ISSUE TITLE
Add POOCH: Pooch

### ISSUE THREAD

**Issue by 0xPooch** [sushiswap/default-token-list#442]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Fantom
Token Address (checkSum): 0x31A47B49b4DBDC54d403b8c4880Ac9BB1A9EbAE8
Token Name (from contract): Pooch
Token Decimals (from contract): 18
Token Symbol (from contract): POOCH
SushiSwap V2 Pair Address of Token: 0x22b82500174df5351d1314d186a43bebf06be88a

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/386
Link to the official homepage of token: https://poochfund.com
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/pooch
Link to official Twitter account: https://twitter.com/poochftm

**Comment by jiro-ono** [comment]
Added
