### ISSUE TITLE
Add ABI: ABACHI on POLYGON

### ISSUE THREAD

**Issue by 0xigor** [sushiswap/default-token-list#443]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: `POLYGON`
Token Address (checkSum): `0x6d5f5317308C6fE7D6CE16930353a8Dfd92Ba4D7`
Token Name (from contract): `Abachi`
Token Decimals (from contract): `9`
Token Symbol (from contract): `ABI`
SushiSwap V2 Pair Address of Token: `0x81FD1d6D336C3a8a0596BAdC664eE01269551130`

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/387
Link to the official homepage of token: https://www.abachi.io/
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/abachi/
Link to official Twitter account: https://twitter.com/Abachi_io

**Comment by jiro-ono** [comment]
Added
