### ISSUE TITLE
Add GRAPE: Grape Finance & WINE: Wine Shares tokens

### ISSUE THREAD

**Issue by grapefi** [sushiswap/default-token-list#444]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Avalanche
Token Address (checkSum): 0x5541D83EFaD1f281571B343977648B75d95cdAC2
Token Name (from contract): Grape Finance
Token Decimals (from contract): 18
Token Symbol (from contract): GRAPE
SushiSwap V2 Pair Address of Token: 0x250CD25f33bAf60AD2768d0a6A492B074d8A25a0

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/390
Link to the official homepage of token: https://grapefinance.app/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/grape-finance
Link to official Twitter account: https://twitter.com/grape_finance

Network: Avalanche
Token Address (checkSum): 0xC55036B5348CfB45a932481744645985010d3A44
Token Name (from contract): Wine Shares
Token Decimals (from contract): 18
Token Symbol (from contract): WINE
SushiSwap V2 Pair Address of Token: 0x250CD25f33bAf60AD2768d0a6A492B074d8A25a0

Link to sushiswap/assets PR: https://github.com/sushiswap/assets/pull/390
Link to the official homepage of token: https://grapefinance.app/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/wine-shares
Link to official Twitter account: https://twitter.com/grape_finance

**Comment by jiro-ono** [comment]
Added
