### ISSUE TITLE
Add {RVRS}: {Reverse Token}

### ISSUE THREAD

**Issue by SquidFinder** [sushiswap/default-token-list#446]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Sushi default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: Harmony One 
Token Address (checkSum): 0xED0B4b0F0E2c17646682fc98ACe09feB99aF3adE
Token Name (from contract): Reverse Token 
Token Decimals (from contract): 18
Token Symbol (from contract): RVRS 
SushiSwap V2 Pair Address of Token: 0xCDe0A00302CF22B3Ac367201FBD114cEFA1729b4

Link to sushiswap/assets PR: https://github.com/sushiswap/default-token-list/pull/445
Link to the official homepage of token: https://app.reverseprotocol.one/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/reverse-protocol
Link to official Twitter account: https://twitter.com/RVRSProtocol?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor

**Comment by jiro-ono** [comment]
@SquidFinder throw the logo up in a PR in this repo (png is needed there): https://github.com/sushiswap/assets

**Comment by jiro-ono** [comment]
Added
