### ISSUE TITLE
Add ⚗️ : ALCHEMIST

### ISSUE THREAD

**Issue by wtfix** [sushiswap/default-token-list#59]
- [ x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x ] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x88acdd2a6425c3faae4bc9650fd7e27e0bebb7ab
Token Name (from contract): Alchemist
Token Decimals (from contract): 18
Token Symbol (from contract): ⚗️
SushiSwap V2 Pair Address of Token: 0x21c48840bb382c9e15120a7c9b9a6cf99a5d1a93

Link to the official homepage of token: http://alchemist.wtf
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/alchemist

**Comment by matthewlilley** [comment]
Added!
