### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by PixiuSwapToken** [sushiswap/default-token-list#74]
- [x] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 
Token Name (from contract): 
Token Decimals (from contract): 
Token Symbol (from contract): 
SushiSwap V2 Pair Address of Token: 

Link to the official homepage of token:
Link to CoinMarketCap or CoinGecko page of token:

**Comment by pixiuswap** [comment]
Please provide the following information for your token.

Token Address: https://bscscan.com/token/0xb80a8edd3730d82a941a1cdd7547e843fd5ca65c
Token Name (from contract): 0xb80a8edd3730d82a941a1cdd7547e843fd5ca65c
Token Decimals (from contract): 8
Token Symbol (from contract): DIO
SushiSwap V2 Pair Address of Token: BNB/DIO

Link to the official homepage of token: https://www.deimostoken.com/
Link to CoinMarketCap or CoinGecko page of token: https://www.coingecko.com/en/coins/deimos-token
