### ISSUE TITLE
Add {MASQ}: {MASQ}

### ISSUE THREAD

**Issue by kauri-hero** [sushiswap/default-token-list#93]
- [Y] I understand that token listing is not required to use the SushiSwap Interface with a token.
- [Y] I understand that filing an issue or adding liquidity does not guarantee addition to the Uniswap default token list.
- [Y] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address: 0x06F3C323f0238c72BF35011071f2b5B7F43A054c
Token Name (from contract): MASQ
Token Decimals (from contract): 18
Token Symbol (from contract): MASQ
SushiSwap V2 Pair Address of Token: https://analytics.sushi.com/tokens/0x06f3c323f0238c72bf35011071f2b5b7f43a054c

Link to the official homepage of token: https://masq.ai
Link to CoinMarketCap or CoinGecko page of token: https://coinmarketcap.com/currencies/masq/

Also here is a link to the PR we submitted on the fork of https://github.com/sushiswap/assets

https://github.com/sushiswap/assets/pull/86

**Comment by matthewlilley** [comment]
Added!
